version: '3.2'

services:
  apiserver:
    image: "${DOCKER_REPOSITORY_PREFIX}apiserver:${DOCKER_TAG}"
    command: /app/app.py
    environment:
      - API_SERVER_PORT
    ports:
      - "${API_SERVER_PORT}:5000"
    restart: always
  frontserver:
    image: "${DOCKER_REPOSITORY_PREFIX}apiserver:${DOCKER_TAG}"
    command: nginx -g 'daemon off;'
    ports:
      - "${MAIN_APP_PORT}:8080"
    depends_on:
      - apiserver
      - webclient
    restart: always
  webclient:
    image: "${DOCKER_REPOSITORY_PREFIX}apiserver:${DOCKER_TAG}"
    command: nginx -g 'daemon off;'
    ports:
      - "${UF_CLIENT_PORT}:8080"
    restart: always
